name: 生成 Changelog 并发布版本

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  workflow_call:
    inputs:
      runid:
        required: true
        type: string

permissions:
  contents: write

jobs:
  generate-changelog-and-release:
    name: 生成 Changelog 并发布版本
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置 git-cliff
        uses: kenji-miyake/setup-git-cliff@v1

      - name: 生成 changelog
        id: generate-changelog
        run: |
          git cliff

      - name: 准备发布
        run: |
          mkdir release
          mkdir artifacts

      - name: 下载 artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          run-id: ${{ github.event.workflow_run.id }}

      - name: 准备 artifacts 
        run: |
          mv artifacts/windows-2022-x64-dir/* release/
          mv artifacts/windows-2022-x86-dir/* release/
          mv artifacts/windows-2022-x64-onefile/* release/
          mv artifacts/windows-2022-x86-onefile/* release/

      - name: 计算 SHA256 值
        run: |
          cd release
          for file in *; do
            sha256sum "$file" >> SHA256SUMS.txt
          done
          cat SHA256SUMS.txt
          
      - name: 验证 SHA256SUMS.txt 文件
        run: |
          cd release
          if [ ! -f "SHA256SUMS.txt" ]; then
            echo "错误：在release目录中未找到SHA256SUMS.txt文件"
            exit 1
          fi
          cd ..

      - name: 生成 需发布 的表格信息
        run: |
          # 手动设置上一个版本号
          PREVIOUS_TAG=v1.1.2.0-beta
          echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_ENV
          cd release
          echo "" >> ../CHANGELOG.md
          echo "Full Changelog: [${{ env.PREVIOUS_TAG }}...${{ github.ref_name }}](https://github.com/SECTL/SecRandom/compare/${{ env.PREVIOUS_TAG }}...${{ github.ref_name }})" >> ../CHANGELOG.md
          echo "" >> ../CHANGELOG.md
          echo "**国内 下载链接**" >> ../CHANGELOG.md
          echo "| 平台/打包方式 | 支持架构 | 完整版 |" >> ../CHANGELOG.md
          echo "| --- | --- | --- |" >> ../CHANGELOG.md
          echo "| Windows | x86, x64 | [下载](https://www.123684.com/s/9529jv-U4Fxh) |" >> ../CHANGELOG.md
          echo "" >> ../CHANGELOG.md
          echo "**Github 镜像 下载链接**" >> ../CHANGELOG.md
          echo "| 镜像源 | 平台/打包方式 | 支持架构 | 完整版 |" >> ../CHANGELOG.md
          echo "| --- | --- | --- | --- |" >> ../CHANGELOG.md
          echo "| ghfast.top | Windows 目录模式 | x86 | [下载 ${{ github.ref_name }}](https://ghfast.top/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x86-dir.zip) |" >> ../CHANGELOG.md
          echo "| ghfast.top | Windows 目录模式 | x64 | [下载 ${{ github.ref_name }}](https://ghfast.top/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x64-dir.zip) |" >> ../CHANGELOG.md
          echo "| ghfast.top | Windows 单文件模式 | x86 | [下载 ${{ github.ref_name }}](https://ghfast.top/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x86-onefile.zip) |" >> ../CHANGELOG.md
          echo "| ghfast.top | Windows 单文件模式 | x64 | [下载 ${{ github.ref_name }}](https://ghfast.top/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x64-onefile.zip) |" >> ../CHANGELOG.md
          echo "| gh-proxy.com | Windows 目录模式 | x86 | [下载 ${{ github.ref_name }}](https://gh-proxy.com/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x86-dir.zip) |" >> ../CHANGELOG.md
          echo "| gh-proxy.com | Windows 目录模式 | x64 | [下载 ${{ github.ref_name }}](https://gh-proxy.com/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x64-dir.zip) |" >> ../CHANGELOG.md
          echo "| gh-proxy.com | Windows 单文件模式 | x86 | [下载 ${{ github.ref_name }}](https://gh-proxy.com/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x86-onefile.zip) |" >> ../CHANGELOG.md
          echo "| gh-proxy.com | Windows 单文件模式 | x64 | [下载 ${{ github.ref_name }}](https://gh-proxy.com/https://github.com/SECTL/SecRandom/releases/download/${{ github.ref_name }}/SecRandom-Windows-${{ github.ref_name }}-x64-onefile.zip) |" >> ../CHANGELOG.md
          echo "" >> ../CHANGELOG.md
          echo "**SHA256 校验值-请核对下载的文件的SHA256值是否正确**" >> ../CHANGELOG.md
          echo "| 文件名 | SHA256 值 |" >> ../CHANGELOG.md
          echo "| --- | --- |" >> ../CHANGELOG.md
          while read -r line; do
            hash=$(echo "$line" | awk '{print $1}')
            file=$(echo "$line" | awk '{print $2}')
            echo "| $file | $hash |" >> ../CHANGELOG.md
          done < SHA256SUMS.txt
          rm SHA256SUMS.txt
          cd ..
            
      - name: 确定发布类型
        id: release-type
        run: |
          if [[ "${{ github.ref }}" == *"beta"* || "${{ github.ref }}" == *"alpha"* ]]; then
            echo "is_beta=true" >> $GITHUB_ENV
          else
            echo "is_beta=false" >> $GITHUB_ENV
          fi

      - name: 发布
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.Releases_BOT }}
          files: release/*
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ env.is_beta == 'true' }}
          tag_name: ${{ github.ref_name }}
          name: SecRandom 新版本 - ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}